site_name: Christina's Travel Notes
nav:
  - Home: index.md
  - East Coast: east-coast.md
  - Midwest Cities: midwest-cities.md
  - Wisconsin: wisconsin.md
  - Pacific Northwest: pac-nw.md
  - California: california.md
  - Other Canada: canada.md
  - British Isles: british-isles.md
  - Hungary: hungary.md
  - Other Europe: other-europe.md
theme: readthedocs
